version: 2.1

orbs:
  conftest: kenfdev/conftest-orb@dev:alpha

executors:
  machine:
    machine:
      image: ubuntu-1604:201903-01

jobs:
  build:
    executor: machine
    steps:
      - checkout
      - run:
          name: Dockerhub login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Run docker registry
          command: docker run -d --rm -p 5000:5000 -v $(pwd)/registry:/var/lib/registry --name registry registry:2
      - conftest/install
      - conftest/push:
          repository: 127.0.0.1:5000/policies:latest
          path: policy
      - run:
          name: Build docker image
          command: docker build -t kenfdev/circleci-orbs-policies:latest .
      - run:
          name: Push docker image
          command: docker push kenfdev/circleci-orbs-policies:latest
